FORMAT: 1A
HOST: https://www.hikalu.com

# XPAUSER
XPA Mobile User API is an *api allowing users to register and log into XPA* 


Authentication works by passing a valid authentication cookie when accessing any secure resources. 
When the client authenticates using the username or oauth login it will receive a cookie. That cookie needs to be included in all requests in the header. 

Once authenticated use the test method below to validate you can call a secure resource. 
If you use the generated curl examples remember to include


- `--insecure -k` As the resource is using SSL 
- `Cookie` Ensure you have the valid cookie in the header. You can get this cookie by using the curl login method on username login which saves it to a file. Remember also to use the correct cookie name. sit = xpa-sit

I have added the calls to the Chrome plugin 'POSTMAN' and for each API I have added links to the calls in Postman. To use these add Postman (the full stand alone version, but not paid) and use the url for the API to access the calls

# Group User API
Notes related resources of the **XPA Mobile User API**
Users have to log into the API using either OAuth2 (Google) or Username and Password. As part of the response the cookie file is returend. The cookie contains the session id with the cookie id. 

## XPA registration using username and password [/mobile/register]
### Register a new user with XPA using Username and Password [PUT]

This resource has the following attributes

- `email` The email address of the user. Signup will be rejected if an existing user record with a matching email address is found
- `firstName` The first name of the user
- `lastName` The surname of the user
- `password` The password used to authenticate the user. The password must be at least 8 characters long and contain at least 2 digits
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `cc` (Optional) The country code E.g GB TODO provide a call for all country codes
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `distance` (Optional) Units for distance MILES, KILOMETERS
- `time` (Optional) Units for time DAY HOUR MINUTES
- `taxName` (Optional) Name of the tax, e.g vat or gst 
- `taxPercentage` (Optional) ercentage of the tax numeric so 20% will be 20
- `tags` (Optional) comma seperated list of tags 


The 409 response is returned if a user with a matching email address already exists. 


Curl example: 


`curl -i -c cookies.txt -k --insecure -X PUT -H "Content-Type: application/json" -d '{"firstName":"Darth","lastName":"Vader","email":"shawn@expensepa.com", "password":"password123", "ccy":"GBP","cc":"GB","distance":"kilometers","time":"day","tax":"vat", "taxPercentage":"20", "tags":"Entertainment , Holidays, Food"}' https://hikalu.com/mobile/register`

+ Request (application/json)

        {
            "firstName": "Darth",
            "lastName": "Vader",
            "email": "shawn@expensepa.com",
            "password": "password123",
            "ccy": "GBP",
            "cc": "GB",
            "distance": "kilometers",
            "time": "day",
            "tax": "vat",
            "taxPercentage": "20"
        }

+ Response 200 
    + Headers

            Set-Cookie: set-cookie: xpa-sit={temporary-token}; path=/; expires=Mon, 30-Jul-2015 09:12:42 GMT; secure; HttpOnly

            
    
    + Body
     
            {
                "message":"Successfully registered user shawn@expensepa.com",
                "id":21,
                "session":"e81aca03e0decf8174c166265a0afe602e99b8f19057970fa6a03c191b628c7a1f0991c52d3b04a07a1c937019f46d68ccd3787240b52f54768db5969a4b9cfb768f7c3c78359af4e56779b640ebc86cbe1a373cd79524f3"
            }
        
+ Response 409

        {
            "message" : "The email address mickey@disney.com is already registered. You may try a different email address."
        }
        
## Login using username and password [/mobile/login/userpass]
Logout for all users 

Curl Example:

`curl -c cookies.txt -k --insecure -X POST  -H "Content-Type: application/json" -d  '{"username":"shawn@expensepa.com", "password":"password123"}'   https://hikalu.com/mobile/login/userpass`


### Login using username and password [POST]

+ Request
    
        {
            {"username":"shawn@expensepa.com", "password":"password123"}'
        }
    
+ Response 200 (application/json)
    + Headers

            Set-Cookie: set-cookie: xpa-sit={temporary-token}; path=/; expires=Mon, 30-Jul-2015 09:12:42 GMT; secure; HttpOnly


  
    + Body

            {
                "session":"1db43880c3e4dad3c28f2e695e309191c409925eabebfaaf54c527f08fe21c26cd0ef9d665cab57ee97d7cc2612b526b5e4f68b831421bf08ab3259587ad1f3d46961a03c5bb375b958bc19e6d2e10b99103707a77e0c8d5"
            }
            
    + Response 400 (application/json)
    
            {
                "message": "Invalid Credentials"
            }


        

## User login using Google Oauth 2 [/authenticateMobile/google]
Login a user with OAuth2 using google. 
Firstly you need to get the token from Google. This is only valid if you have already registered using google OAuth2 (Not sure yet how the mobile client is going to perform this? ) 

This resource has the following attributes

- `accessToken` The token retreived from google or the OAuth2 provider 

Curl Example:

`curl -c cookies.txt -k --insecure -X POST -H "Accept: Application/json" -H "Content-Type: application/json" https://hikalu.com/authenticateMobile/google -d '{"accessToken":"ya29.IwC-wm_3l7zbDxoAAADtR3LL47wt4zYLmOoliwJiB9_bUAkcG0RdK-a9ZrCLVg"}' | grep }| python -mjson.tool`


If it does not authenticate and you get some json error message it means the authentication is wrong. Double check that your access token is correct. Restart memcached and delete all cookies, then re login and get the value out of the database which is sent from Google


### Login using Google OAuth2 [POST]

+ Request

            {
                "accessToken":"ya29.QwAj-1XHJe_ssiEAAABF-OQTIt0rwGsUaymqZSKOjgu1iN9iNslGLpV3QAxGcf0yHeHbUmHkIgyzYVagkDI"
            }   
    
+ Response 200 (application/json)

    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

    + Body

            {
                "sessionId": "7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59"
            }
            
    + Response 404 (application/json)
    
            {
                "error": "user not found"
            }

## XPA partila update of user [/mobile/user/edit/{id}]
### Update a user [POST]

This resource has the following attributes

- `email` (Optional) The email address of the user. Signup will be rejected if an existing user record with a matching email address is found
- `firstName` (Optional) The first name of the user
- `lastName` (Optional) The surname of the user
- `password` (Optional) The password used to authenticate the user. The password must be at least 8 characters long and contain at least 2 digits
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `cc` (Optional) The country code E.g GB TODO provide a call for all country codes
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `distance` (Optional) Units for distance MILES, KILOMETERS
- `time` (Optional) Units for time DAY HOUR MINUTES
- `taxName` (Optional) Name of the tax, e.g vat or gst 
- `taxPercentage` (Optional) ercentage of the tax numeric so 20% will be 20
- `tags` (Optional) comma seperated list of tags 


The 409 response is returned if a user with a matching email address already exists. 


Curl example: 


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d  '{"firstName":"Darth renamed"}'   https://hikalu.com/mobile/user/edit/3`


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d  '{"tags":"Entertainment , Holidays, Food"}'   https://hikalu.com/mobile/user/edit/21`




+ Parameters
    + id (string, required, `numerice value representing a long`) ... The id of the `user` to retrieve



+ Request (application/json)

    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

    + Body


            {
                "id": "23",
                "firstName": "Darth",
                "lastName": "Vader",
                "email": "shawn@expensepa.com",
                "password": "password123",
                "ccy": "GBP",
                "cc": "GB",
                "distance": "kilometers",
                "time": "day",
                "tax": "vat",
                "taxPercentage": "20"
            }

+ Response 200 (application/json)

        {
            "message":"Successfully updated user",
            "id":"41"
        }
        
+ Response 404

        {
            "message" : "User does not exist"
        }

## Logout for all [/mobile/logout]
Logout for all users 

Curl Example:

`curl -b cookies.txt -c cookies.txt -i -H -k  --insecure -X POST https://hikalu.com/mobile/logout`


### Logout [POST]

+ Request 
    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

    
+ Response 200 (application/json)

  
    + Body

            {
                "message":"successfully logged out"
            }
            
    + Response 401 (application/json)
    
            {
                "error": "Credentials required"
            }


## Test calls to validate authentication [/test]
Test calls to test that you can call secured resources

Curl Example:

`curl -b cookies.txt -c cookies.txt -i -H -k --insecure -X GET https://hikalu.com/test`  (Test using HTTP GET)


`curl -b cookies.txt -c cookies.txt -i -H -k --data "email=s@junocube.com"  --insecure -X POST https://hikalu.com/test`   (Test using HTTP POST with params returning JSON)


`curl -i -H -k --insecure --cookie "xpa-sit=4af352e0fde5f81ba7e27a28f26b2e60a3be125c9c628c114acb0adaa8d154ceb241dcb97514c1ef437227efc320296f2036324be5af3a4c3dfb3d3ecfdc1cca6fbb200f0fe9ab848f132a580c01d04b77dd6bbeddd4a5d2" -X GET https://hikalu.com/test`  (Test using HTTP GET with cookie/sessionId in the command and not in the text file)


`curl --include --insecure -k --header "Cookie: xpa-dev=1ac3bce59a423d8728478b027ce64a65408fa0e6991dba8b701caaa20c0db919e501a7727560795dc11407cefc8cfc6f00c7e5845cfbe15fb1db9813f8db2cd9981730821ff0f7ef6cddc525b63bd2cfa5d00a72a419f8e8" https://localhost:9443/test`

### Logout using Google OAuth2 [GET]

+ Request
    
    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

    
+ Response 200 (application/json)


    + Body
    
            {"1":{"name":"hello2"}}


# Group Receipt API
Notes related resources of the **XPA Mobile User API**
Users have to log into the API using either OAuth2 (Google) or Username and Password. As part of the response the cookie file is returend. The cookie contains the session id with the cookie id. 


## New Receipt [/mobile/add/receipt]
### Add a new Receipt representing a receipt [PUT]


This resource has the following attributes

- `name` (Required) name of the receipt
- `description`  (Required)  Description of the receipt
- `amount` (Required)  Amount in double representing a currency value. I.e 103.00 or 33.12 
- `ccy` (Required) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `tags` (Optional) comma seperated list of tags. A tag is what you tag the receipt as, E.g Entertainment 
- `created` (Optional) date the receipt was created, defaults to the current date if not provided


Curl example:


`curl -v -b cookies.txt -c cookies.txt -i  -k --insecure -X PUT -H "Content-Type: application/json" -d '{"name":"Dinner with Alina","description":"First ever receipt from a mobile device","amount":"55.90", "":"", "tags": "tag1, tag 2, tag - 5", "created":"2014-07-11T09:04:56.123", "ccy":"GBP"}'   https://hikalu.com/mobile/add/receipt`


+ Request (application/json)
    
    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

    + Body
    
            {
                "name": "Lunch at Harrods",
                "description": "Met with Ahmad to discuss the terms of the contract",
                "amount": "55.56",
                "ccy": "GBP",
                "tags": "lunch, entertainment, project dark star",
                "created": "2014-07-11T09:04:56.123"
            }

+ Response 200 (application/json)

            {
                "message":"Successfully added receipt 'Dinner with Alina'",
                "id":41
            }
        

+ Response 400 (application/json)

            {
                "message":"Some mandatory fields not provided: name=null, description=First ever receipt from a mobile device, amount=null"
            }
            
## New Time Receipt [/mobile/add/time]
### Add a new Receipt representing an receipt for time [PUT]


This resource has the following attributes

- `name` (Required) name of the receipt
- `description`  (Required)  Description of the receipt
- `timeUnit` (Required) the units the time will be calculated in. Supported values are MINUTE, HOUR & DAY
- `time` (Required) actual time in decimal format. E.g 1 or 1.4 etc
- `timeRate` (Required) The charge per unit. E.g if the ccy is £ the unit HOUR and the time rate 10 then this will be £10 per hour
- `ccy` (optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  Default will be used if not provided
- `amount` (optional)  If amount is not provide it will be calculated from the time units and amount
- `tags` (Optional) comma seperated list of tags. A tag is what you tag the receipt as, E.g Entertainment 
- `created` (Optional) date the receipt was created, defaults to the current date if not provided

Curl example:


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X PUT -H "Content-Type: application/json" -d '{"name":"Time worked on project xyz","description":"Working really hard on this", "tags": "tag1, tag 2, tag - 5", "created":"2014-07-11T09:04:56.123", "ccy":"GBP", "timeUnit":"HOUR","time":"10", "timeRate":"55.50"}'   https://hikalu.com/mobile/add/time`


+ Request (application/json)

        {
            "name": "UI Design for XPA",
            "description": "Designed the UI for James on the XPA receipt input screen",
            "timeUnit": "DAY",
            "time": "5",
            "timeRate": "250",
            "tags": "API Design, API 2014, Work",
            "created": "2014-07-11T09:04:56.123"
        }

+ Response 200 (application/json)

            {
                "message":"Successfully added receipt 'UI Design for XPA'",
                "id":41
            }
        

+ Response 400 (application/json)

            {
                "message":"Some mandatory fields not provided: name=null, description=First ever receipt from a mobile device, amount=null"
            }     
            

## New Distance Receipt [/mobile/add/distance]
### Add a new Receipt representing a receipt for milage/distance [PUT]


This resource has the following attributes

- `name` (Required) name of the receipt
- `description`  (Required)  Description of the receipt
- `units` (Required) the units the time will be calculated in. Supported values are MILES & KILOMETERS
- `distance` (Required) actual distance 105
- `distanceRate` (Required) The charge per unit. E.g if the ccy is £ the units KILOMETER and the distanceRate is 0.30 then this will be £0.30 per kilometer
- `ccy` (optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  Default will be used if not provided
- `amount` (optional)  If amount is not provide it will be calculated from the time units and amount
- `tags` (Optional) comma seperated list of tags. A tag is what you tag the receipt as, E.g Entertainment 
- `created` (Optional) date the receipt was created, defaults to the current date if not provided

Curl example:


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X PUT -H "Content-Type: application/json" -d '{"name":"Time worked on project xyz","description":"Working really hard on this", "tags": "tag1, tag 2, tag - 5", "created":"2014-07-11T09:04:56.123", "ccy":"GBP", "units":"KILOMETERS","distance":"589", "distanceRate":"55.50"}'   https://hikalu.com/mobile/add/distance`



+ Request (application/json)

        {
            "name": "Weekly travel for XPA",
            "description": "Travel between clients sites while desiging the API for XPA",
            "units": "KILOMETERS",
            "distance": "512",
            "distanceRate": "0.32",
            "tags": "Travel-2014, Travel XPA, Work",
            "created": "2014-07-11T09:04:56.123"
        }
        
       
+ Response 200 (application/json)

            {
                "message":"Successfully added receipt 'Weekly travel for XPA'",
                "id":41
            }
        

+ Response 400 (application/json)

            {
                "message":"Some mandatory fields not provided: name=null, description=First ever receipt from a mobile device, amount=null"
            }    
  
  
## Update Receipt [/mobile/receipt/update/{receiptType}/{id}]
### Update receipt [POST]


Receipt type can be the following values


- `receiptType` receipt
- `receiptType` time
- `receiptType` distance


This resource has the following attributes


- `name` (Optional) name of the receipt
- `description`  (Optional)  Description of the receipt
- `amount` (Optional)  Amount in double representing a currency value. I.e 103.00 or 33.12 
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `tags` (Optional) comma seperated list of tags. A tag is what you tag the receipt as, E.g Entertainment. The tags provided will update the tags on the receipt 
- `units` (Optional) the units the time will be calculated in. Supported values are MILES & KILOMETERS
- `distance` (Optional) actual distance 105
- `distanceRate` (Optional) The charge per unit. E.g if the ccy is £ the units KILOMETER and the distanceRate is 0.30 then this will be £0.30 per kilometer
- `timeUnit` (Optional) the units the time will be calculated in. Supported values are MINUTE, HOUR & DAY
- `time` (Optional) actual time in decimal format. E.g 1 or 1.4 etc
- `timeRate` (Optional) The charge per unit. E.g if the ccy is £ the unit HOUR and the time rate 10 then this will be £10 per hour
- `created` (Optional) date the receipt was created, defaults to the current date if not provided

Curl example:


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d '{ "name":"Changrom a mobile device","amount":"55.21", "tags":"new45555"}'   https://hikalu.com/mobile/receipt/update/receipt/44`


+ Request (application/json)

        {
            "name": "Lunch at Harrods",
            "description": "Met with Ahmad to discuss the terms of the contract",
            "amount": "55.56",
            "ccy": "GBP",
            "tags": "lunch, entertainment, project dark star"
        }

+ Response 200 (application/json)

            {
                "message":"Successfully updated receipt"",
                "id":44
            }
        

+ Response 404 (application/json)

            {
                "message":"Receipt id=9999 not found""
            }
              
            
## Upload image for receipt [/receipt/upload]
### Add an image to a receipt [POST]  

This is a form submit with two parameters. Please have a look at the curl example 

Curl Example:

`curl -b cookies.txt -c cookies.txt -i -k --insecure -X POST -F "id=103" -F "image=@/Users/skywalker/Dropbox/receipt-images/photo-33.JPG" https://hikalu.com/receipt/upload`


+ Request 

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body
    
            {
                "id": "(Required id of the receipt to attach the image to)",
                "image": "@full path to the image see example"
            }        

+ Response 200 (application/json)

        {
            "status":"SUCCESS",
            "image":{"imageId":"778e8d48-4364-4a44-9c8e-0f3dcce4df9f", "name":"photo-33.JPG"}
        }
        
        
    
        
## Delete a receipt [/mobile/receipt/delete/{id}]
### Delete a receipt [DELETE]     

Curl Example:

`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X DELETE  https://hikalu.com/mobile/receipt/delete/104`


+ Request

            Content-Type: application/json
            Accept: application/json
            
    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79


+ Response 200 (application/json)


        {
            "message":"Deleted receipt with id=104"
        }
        
+ Response 404 (application/json)


        {
            "message":"Receipt id=104 not found"
        }    
        

## Search Receipts [/mobile/receipt/search/{receiptType}]
### Search for receipts [POST]    

Receipt type can be the following values


- `receiptType` receipt
- `receiptType` time
- `receiptType` distance
- `receiptType` all

This resource has the following attributes

- `from` (Required in date format )  DateTime format required "2013-03-30T09:04:56.123" The date to search from
- `includeAttached` (Optional defaults to true)  Include receipts that are already attached to reports. (false if you want to attach receipt to report as the receipt can only be attached to one report)
- `to`  (optional) DateTime format required "2013-03-30T09:04:56.123" If provided will search between two dates. If not provided will search from the from date to the current date
- `limit` (optional) the amount of results to limit. If not provided defaults to system default


Curl examples:

`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d '{"from":"2013-03-30T09:04:56.123", "limit":"100"}'   https://hikalu.com/mobile/receipt/search/all`


`curl -b cookies.txt -c cookies.txt -i -k --insecure -X POST -H "Content-Type: application/json" -d '{"from":"2013-03-30T09:04:56.123", "limit":"100", "includeAttached":"false"}' https://hikalu.com/mobile/receipt/search/all`
+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "name": "Lunch at Harrods",
                "description": "Met with Ahmad to discuss the terms of the contract",
                "amount": "55.56",
                "ccy": "GBP",
                "tags": "lunch, entertainment, project dark star"
            }
        
+ Response 200 (application/json)
        

        [
          {
            "id": 103,
            "name": "Changed name again",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 55556.9,
            "currency": "GBP",
            "status": "SAVED",
            "type": "DISTANCE",
            "units": "KILOMETERS",
            "distance": 589,
            "distanceRate": 55.5,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 04:06",
            "count": 2,
            "tags": [
              {
                "id": 127,
                "name": " tag 2",
                "timestamp": 1405430006157
              },
              {
                "id": 128,
                "name": "tag1",
                "timestamp": 1405430006158
              },
              {
                "id": 129,
                "name": " tag - 5",
                "timestamp": 1405430006158
              }
            ],
            "imageIds": [
              {
                "id": "c9d11bd3-8c77-41c3-af4a-401cdb000f0a",
                "image": null,
                "imageName": "harrods-large.JPG",
                "contentType": "image\/jpeg",
                "imageStoreId": null,
                "deleted": false,
                "timestamp": 1405430836834,
                "imageBytes": null
              },
              {
                "id": "778e8d48-4364-4a44-9c8e-0f3dcce4df9f",
                "image": null,
                "imageName": "photo-33.JPG",
                "contentType": "image\/jpeg",
                "imageStoreId": null,
                "deleted": false,
                "timestamp": 1405430700164,
                "imageBytes": null
              }
            ],
            "lastUpdated": 1405436809468,
            "allImageIds": [
              {
                "id": "c9d11bd3-8c77-41c3-af4a-401cdb000f0a",
                "image": null,
                "imageName": "harrods-large.JPG",
                "contentType": "image\/jpeg",
                "imageStoreId": null,
                "deleted": false,
                "timestamp": 1405430836834,
                "imageBytes": null
              },
              {
                "id": "778e8d48-4364-4a44-9c8e-0f3dcce4df9f",
                "image": null,
                "imageName": "photo-33.JPG",
                "contentType": "image\/jpeg",
                "imageStoreId": null,
                "deleted": false,
                "timestamp": 1405430700164,
                "imageBytes": null
              }
            ],
            "selectedTags": " tag - 5,tag1, tag 2",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a355,556.90",
            "euro": false,
            "displayTotal": "\u00a355,556.90",
            "defaultCcyAmount": 55556.9,
            "reportIds": "[]"
          },
          {
            "id": 102,
            "name": "Time worked on project xyz",
            "description": "Working really hard on this",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 555,
            "currency": "GBP",
            "status": "SAVED",
            "type": "TIME",
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": "HOUR",
            "time": 10,
            "timeRate": 55.5,
            "timestamp": "15-Jul-2014 02:13",
            "count": 0,
            "tags": [
              {
                "id": 124,
                "name": "tag1",
                "timestamp": 1405430003818
              },
              {
                "id": 125,
                "name": " tag 2",
                "timestamp": 1405430003819
              },
              {
                "id": 126,
                "name": " tag - 5",
                "timestamp": 1405430003820
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405430003816,
            "allImageIds": [
              
            ],
            "selectedTags": " tag - 5, tag 2,tag1",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a3555.00",
            "euro": false,
            "displayTotal": "\u00a3555.00",
            "defaultCcyAmount": 555,
            "reportIds": "[]"
          },
          {
            "id": 101,
            "name": "Time worked on project xyz",
            "description": "Working really hard on this",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 555,
            "currency": "GBP",
            "status": "SAVED",
            "type": "TIME",
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": "HOUR",
            "time": 10,
            "timeRate": 55.5,
            "timestamp": "15-Jul-2014 02:13",
            "count": 0,
            "tags": [
              {
                "id": 121,
                "name": " tag 2",
                "timestamp": 1405430002057
              },
              {
                "id": 122,
                "name": " tag - 5",
                "timestamp": 1405430002058
              },
              {
                "id": 123,
                "name": "tag1",
                "timestamp": 1405430002058
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405430002054,
            "allImageIds": [
              
            ],
            "selectedTags": "tag1, tag - 5, tag 2",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a3555.00",
            "euro": false,
            "displayTotal": "\u00a3555.00",
            "defaultCcyAmount": 555,
            "reportIds": "[]"
          },
          {
            "id": 81,
            "name": "Time worked on project xyz",
            "description": "Working really hard on this",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 32689.5,
            "currency": "GBP",
            "status": "SAVED",
            "type": "DISTANCE",
            "units": "KILOMETERS",
            "distance": 589,
            "distanceRate": 55.5,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 02:13",
            "count": 0,
            "tags": [
              {
                "id": 101,
                "name": " tag 2",
                "timestamp": 1405429989681
              },
              {
                "id": 102,
                "name": " tag - 5",
                "timestamp": 1405429989682
              },
              {
                "id": 103,
                "name": "tag1",
                "timestamp": 1405429989684
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405429989678,
            "allImageIds": [
              
            ],
            "selectedTags": "tag1, tag - 5, tag 2",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a332,689.50",
            "euro": false,
            "displayTotal": "\u00a332,689.50",
            "defaultCcyAmount": 32689.5,
            "reportIds": "[]"
          },
          {
            "id": 62,
            "name": "Time worked on project xyz",
            "description": "Working really hard on this",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 32689.5,
            "currency": "GBP",
            "status": "SAVED",
            "type": "DISTANCE",
            "units": "KILOMETERS",
            "distance": 589,
            "distanceRate": 55.5,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 02:06",
            "count": 0,
            "tags": [
              {
                "id": 84,
                "name": " tag 2",
                "timestamp": 1405429594904
              },
              {
                "id": 85,
                "name": "tag1",
                "timestamp": 1405429594905
              },
              {
                "id": 86,
                "name": " tag - 5",
                "timestamp": 1405429594905
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405429594903,
            "allImageIds": [
              
            ],
            "selectedTags": " tag - 5,tag1, tag 2",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a332,689.50",
            "euro": false,
            "displayTotal": "\u00a332,689.50",
            "defaultCcyAmount": 32689.5,
            "reportIds": "[]"
          },
          {
            "id": 61,
            "name": "Time worked on project xyz",
            "description": "Working really hard on this",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 555,
            "currency": "GBP",
            "status": "SAVED",
            "type": "TIME",
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": "HOUR",
            "time": 10,
            "timeRate": 55.5,
            "timestamp": "15-Jul-2014 01:56",
            "count": 0,
            "tags": [
              {
                "id": 81,
                "name": " tag 2",
                "timestamp": 1405429015444
              },
              {
                "id": 82,
                "name": " tag - 5",
                "timestamp": 1405429015445
              },
              {
                "id": 83,
                "name": "tag1",
                "timestamp": 1405429015445
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405429015442,
            "allImageIds": [
              
            ],
            "selectedTags": "tag1, tag - 5, tag 2",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a3555.00",
            "euro": false,
            "displayTotal": "\u00a3555.00",
            "defaultCcyAmount": 555,
            "reportIds": "[]"
          },
          {
            "id": 44,
            "name": "Changed name again",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 55.21,
            "currency": "GBP",
            "status": "SAVED",
            "type": null,
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 04:20",
            "count": 0,
            "tags": [
              {
                "id": 223,
                "name": "new45555",
                "timestamp": 1405441004234
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405437636293,
            "allImageIds": [
              
            ],
            "selectedTags": "new45555",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a355.21",
            "euro": false,
            "displayTotal": "\u00a355.21",
            "defaultCcyAmount": 55.21,
            "reportIds": "[]"
          },
          {
            "id": 43,
            "name": "Dinner with Alina",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": null,
            "currency": "GBP",
            "status": "SAVED",
            "type": null,
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 01:43",
            "count": 0,
            "tags": [
              {
                "id": 47,
                "name": "tag1",
                "timestamp": 1405428215670
              },
              {
                "id": 48,
                "name": " tag 2",
                "timestamp": 1405428215671
              },
              {
                "id": 49,
                "name": " tag - 5",
                "timestamp": 1405428215671
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405428215668,
            "allImageIds": [
              
            ],
            "selectedTags": " tag - 5, tag 2,tag1",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "",
            "euro": false,
            "displayTotal": "",
            "defaultCcyAmount": null,
            "reportIds": "[]"
          },
          {
            "id": 42,
            "name": "Dinner with Alina",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": null,
            "currency": "GBP",
            "status": "SAVED",
            "type": null,
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 01:43",
            "count": 0,
            "tags": [
              {
                "id": 44,
                "name": "tag1",
                "timestamp": 1405428189944
              },
              {
                "id": 45,
                "name": " tag 2",
                "timestamp": 1405428189945
              },
              {
                "id": 46,
                "name": " tag - 5",
                "timestamp": 1405428189945
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405428189942,
            "allImageIds": [
              
            ],
            "selectedTags": " tag - 5, tag 2,tag1",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "",
            "euro": false,
            "displayTotal": "",
            "defaultCcyAmount": null,
            "reportIds": "[]"
          },
          {
            "id": 41,
            "name": "Dinner with Alina",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 55.9,
            "currency": "GBP",
            "status": "SAVED",
            "type": null,
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 01:39",
            "count": 0,
            "tags": [
              {
                "id": 41,
                "name": " tag - 5",
                "timestamp": 1405427985134
              },
              {
                "id": 42,
                "name": " tag 2",
                "timestamp": 1405427985135
              },
              {
                "id": 43,
                "name": "tag1",
                "timestamp": 1405427985135
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405427985131,
            "allImageIds": [
              
            ],
            "selectedTags": "tag1, tag 2, tag - 5",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a355.90",
            "euro": false,
            "displayTotal": "\u00a355.90",
            "defaultCcyAmount": 55.9,
            "reportIds": "[]"
          },
          {
            "id": 21,
            "name": "Dinner with Alina",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 55.9,
            "currency": "GBP",
            "status": "SAVED",
            "type": null,
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 01:38",
            "count": 0,
            "tags": [
              {
                "id": 21,
                "name": " tag 2",
                "timestamp": 1405427933805
              },
              {
                "id": 22,
                "name": " tag - 5",
                "timestamp": 1405427933806
              },
              {
                "id": 23,
                "name": "tag1",
                "timestamp": 1405427933806
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405427933801,
            "allImageIds": [
              
            ],
            "selectedTags": "tag1, tag - 5, tag 2",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a355.90",
            "euro": false,
            "displayTotal": "\u00a355.90",
            "defaultCcyAmount": 55.9,
            "reportIds": "[]"
          },
          {
            "id": 1,
            "name": "Dinner with Alina",
            "description": "First ever receipt from a mobile device",
            "created": "11-Jul-2014",
            "zone": "Europe\/London",
            "amount": 55.9,
            "currency": "GBP",
            "status": "SAVED",
            "type": null,
            "units": null,
            "distance": null,
            "distanceRate": null,
            "timeUnit": null,
            "time": null,
            "timeRate": null,
            "timestamp": "15-Jul-2014 01:36",
            "count": 0,
            "tags": [
              {
                "id": 1,
                "name": " tag - 5",
                "timestamp": 1405427815868
              },
              {
                "id": 2,
                "name": " tag 2",
                "timestamp": 1405427815872
              },
              {
                "id": 3,
                "name": "tag1",
                "timestamp": 1405427815873
              }
            ],
            "imageIds": [
              
            ],
            "lastUpdated": 1405427815859,
            "allImageIds": [
              
            ],
            "selectedTags": "tag1, tag 2, tag - 5",
            "attachedToReport": false,
            "reportNames": "None",
            "attachedToSubmittedReport": false,
            "displayAmount": "\u00a355.90",
            "euro": false,
            "displayTotal": "\u00a355.90",
            "defaultCcyAmount": 55.9,
            "reportIds": "[]"
          }
        ]


## Search Time/Distance/Quote Receipts [/mobile/receipts/{receiptType}]
### Search for Time/Distance/Quote Receipts [POST]    

Receipt type can be the following values


- `receiptType` quote
- `receiptType` time
- `receiptType` distance
- `receiptType` all

This resource has the following attributes

- `from` (Required in date format )  DateTime format required "2013-03-30T09:04:56.123" The date to search from
- `to`  (optional) DateTime format required "2013-03-30T09:04:56.123" If provided will search between two dates. If not provided will search from the from date to the current date
- `state` (optional) The state of the receipt. Valid values are new, deleted, approved, rejected, pending, submitted, saved. If none provided everything apart from deleted is searched for. To search for deleted you need to explicity search have delted
- `limit` (optional) the amount of results to limit. If not provided defaults to system default


Curl examples:

`curl -b cookies.txt -c cookies.txt -i -k --insecure -X POST -H "Content-Type: application/json" -d '{"from":"2013-03-30", "limit":"100"}' https://hikalu.com/mobile/receipts/distance`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "from": "2013-03-30",
                "limit": "50"
            }
        
+ Response 200 (application/json)
        
            {
                -1: {
                    id: 62
                    name: "First Distance"
                    created: "28-Aug-2014"
                    currency: "USD"
                    total: 490
                    state: "Saved"
                    type: "Distance"
                    notes: " sdfsafdsa"
                    tags: "Travel"
                    timestamp: 1409245251824
                }
            }



## Poll Receipts [/ajax/receipts/{time} ]
### Poll Receipts [GET]    

+ Parameters
    + time (long, required, `numerice value representing a long time since`) ... Get all the receipts since the time

+ Request (application/json)

    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

+ Response 200 (application/json)
         
           {
                "1": {
                    "url": "/receipts#/ajax/receipts/edit/61",
                    "name": "todelete",
                    "id": 61,
                    "timestamp": 1407254741224
                },
                "2": {
                    "url": "/receipts#/ajax/receipts/edit/27",
                    "name": "second",
                    "id": 27,
                    "timestamp": 1406738113161
                },
                "3": {
                    "url": "/receipts#/ajax/receipts/edit/26",
                    "name": "first",
                    "id": 26,
                    "timestamp": 1406738091989
                }
            }




# Group Invoice Report
Report related resources of the **Receipt API**

## Create new Invoice Report [/mobile/report]
### Create new Invoice Report API [PUT]


This resource has the following attributes

- `name` (Required) name of the report
- `type` (Required) the type of the report values are (invoice expense)
- `reportStatus`  (Optional) case sensitive (NEW, SUBMITTED, REJECTED, OPEN)
- `reportType`  (Optional) case sensitive (INVOICE, EXPENSE)
- `date` (Optional) date in the datetime format "2013-03-30T09:04:56.123"
- `discount` (Optional) Numberic discount amount
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `receiptIds` (Optional) comma seperated list of receitp ids to attach to the report
- `notes` (Optional) Notes attached to the report
- `fromEmail` (Optional) if different from the users email
- `toEmail` (Optional) who this report is going to be sent to
- `contactInfo` (Optional) if not provide the default from user will be used


Curl example: 


`curl -b cookies.txt -c cookies.txt -i -k --insecure -X PUT -H "Content-Type: application/json" -d '{"name":"Second Mobile Invoice report","date":"2013-03-30T09:04:56.123", "discount":"100.00", "ccy": "GBP", "receiptIds" : "1,21", "reportType":"INVOICE", "reportStatus":"OPEN"}' https://hikalu.com/mobile/report`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "name": "Invoice",
                "type": "invoice",
                "fromEmail": "shawn@expensepa.com",
                "discount": "100",
                "ccy": "GBP",
                "receiptIds": "1,11,25",
                "notes": "Please settle this invoice by the required time",
                "vat": "20"
            }

+ Response 200 (application/json)

        {
          "message": "Successfully created report Invoice",
          "id":"0e8a4dae-4866-4c94-998c-541cd4910a5f",
          "reportId":1
        }
        
        
+ Response 400 (application/json)

            {"reportType":["Invalid value"],"reportStatus":["Invalid value"]}   

## Delete a Report [/mobile/report/{reportId}]
### Delete Report API [DELETE]

If the report has invoices attached these will be unattached. 
You can not delete the report if its been submitted

Curl example: 


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X DELETE  https://hikalu.com/mobile/report/61`

+ Parameters
    + reportId (long, required, `numerice value representing a long`) ... The id of the `report` to delete


+ Request 

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79


+ Response 200 (application/json)

        {
          "message": "Successfully deleted report id=61"
        }

+ Response 404 (application/json)

        {
          "message": "Report id=100 not found"
        }

+ Response 400 (application/json)

        {
          "message": "Unable to delete resource with status=submitted"
        }


## Update Report [/mobile/report/{reportType}/{id}]
### Update report [POST]


Receipt type can be the following values


- `reportType` invoice
- `reportType` expense



This resource has the following attributes


- `name` (Optional) name of the receipt
- `type`  (Optional) the type of the report values are (invoice expense)
- `reportStatus`  (Optional) case sensitive (NEW, SUBMITTED, REJECTED, OPEN)
- `reportType`  (Optional) case sensitive (INVOICE, EXPENSE)
- `date` (Optional)  date in the datetime format "2013-03-30T09:04:56.123"
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `discount` (Optional) Numberic discount amount
- `receiptIds` (Optional) comma seperated list of receitp ids to attach to the report. Important, if you are adding a receipt you need to provide all the receipt ids
- `notes` (Optional) Notes attached to the report
- `fromEmail` (Optional) if different from the users email
- `toEmail` (Optional) who this report is going to be sent to
- `contactInfo` (Optional) if not provide the default from user will be used


Curl example:


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d '{ "name":"Changrom a mobile device","amount":"55.21", "tags":"new45555"}'   https://hilalu.com/mobile/receipt/update/receipt/44`


+ Request (application/json)

        {
            "name": "Lunch at Harrods",
            "description": "Met with Ahmad to discuss the terms of the contract",
            "amount": "55.56",
            "ccy": "GBP",
            "tags": "lunch, entertainment, project dark star"
        }

+ Response 200 (application/json)

           {
               "message":"Successfully updated report name=Changed report name",
               "id":"ed0777e2-aea5-469e-a57b-ef65da919288",
               "reportId":25
           }
        

+ Response 404 (application/json)

            {
                "message":"Receipt id=9999 not found""
            }
            

+ Response 400 (application/json)

            {"reportType":["Invalid value"],"reportStatus":["Invalid value"]}   
            
            
## Email report [/mobile/report/email/{id}]
### Email report [POST]    

Report can be emailed 

This resource has the following attributes

- `to`  (Required) to email address of who we are sending the report to
- `from` (Optional )  If you want a different from to the address registered on the users account
- `copy`  (Optional) True or False, does the user want to be coppied onto the email i.e sent a copy of the email
- `cc`  (Optional) Any other email addresses to cc the email to
- `memo` (optional) Notes which will appear as text on the email


Curl examples:

`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d '{"to":"svader@gmail.com","from":"svader@gmail.com", "memo":"Pay me now!"}'  https://hikalu.com/mobile/report/email/2`


+ Parameters
    + id (string, required, `numerice value representing a long`) ... The id of the `user` to retrieve


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "name": "Lunch at Harrods",
                "description": "Met with Ahmad to discuss the terms of the contract",
                "amount": "55.56",
                "ccy": "GBP",
                "tags": "lunch, entertainment, project dark star"
            }
        
+ Response 200 (application/json)
        

## Search reports [/mobile/report]
### Search for reports [POST]    

Receipt type can be the following values

This resource has the following attributes


- `from` (Required in date format )  DateTime format required "2013-03-30T09:04:56.123" The date to search from
- `to`  (optional) DateTime format required "2013-03-30T09:04:56.123" If provided will search between two dates. If not provided will search from the from date to the current date
- `reportStatus`  (Optional) case sensitive (NEW, SUBMITTED, REJECTED, OPEN)
- `reportType`  (Optional) case sensitive (INVOICE, EXPENSE)
- `limit` (optional) the amount of results to limit. If not provided defaults to system default


Curl examples:

`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d '{"from":"2013-03-30T09:04:56.123", "limit":"100"}'  https://hikalu.com/mobile/report`

`curl -b cookies.txt -c cookies.txt -i -k --insecure -X POST -H "Content-Type: application/json" -d '{"from":"2013-03-30T09:04:56.123", "limit":"100", "reportStatus":"OPEN", "reportType":"EXPENSE"}' https://hikalu.com/mobile/report`

`curl -b cookies.txt -c cookies.txt -i -k --insecure -X POST -H "Content-Type: application/json" -d '{"from":"2013-03-30T09:04:56.123", "limit":"100"}' https://hikalu.com/mobile/report | grep { | python -mjson.tool`

+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "name": "Lunch at Harrods",
                "description": "Met with Ahmad to discuss the terms of the contract",
                "amount": "55.56",
                "ccy": "GBP",
                "tags": "lunch, entertainment, project dark star"
            }
        
+ Response 200 (application/json)
        

## Poll Reports [//ajax/reports/poll/{time} ]
### Poll Reports [GET]    

+ Parameters
    + time (long, required, `numerice value representing a long time since`) ... Get all the reports since the time

+ Request (application/json)

    + Header

            Set-Cookie: xpa-dev=7291d2e466a8ab2f8e5b2e9af272839d13909690acef9551088ed8c574f97c7bafec62a878ac7ceecc5d6a262528b2889e4fd77438dbfd9ad205220f10162fee55fb41229e8ad73d66975cd123f22f2ffb3268031e4c4e59; Expires=Tue, 15 Jul 2014 21:58:57 GMT; Path=/; Secure; HTTPOnly

+ Response 200 (application/json)
         
            {
                "1": {
                    "url": "/receipts#/report/edit/41",
                    "name": null,
                    "id": 41,
                    "timestamp": 1407313568304
                },
                "2": {
                    "url": "/receipts#/report/edit/7",
                    "name": "second report",
                    "id": 7,
                    "timestamp": 1407254324107
                },
                "3": {
                    "url": "/receipts#/report/edit/9",
                    "name": "First ever receipt",
                    "id": 9,
                    "timestamp": 1407253759028
                },
                "4": {
                    "url": "/receipts#/report/edit/6",
                    "name": "Report for XPA",
                    "id": 6,
                    "timestamp": 1407253068184
                }
            }


# Group Expense Report
Report related resources of the **Receipt API** <br />
Example Rest calls for Postman https://www.getpostman.com/collections/247156b20866ffe056da

## Create new Expense Report [/mobile/report/{reportType}]
### Create new Expense Report API [POST]


This resource has the following attributes

- `name` (Required) name of the report
- `from` (Required) date the report is from in the datetime format "2013-03-30"
- `to` (Required) date the report is to in the datetime format "2014-03-30"
- `reportStatus`  (Optional) case sensitive (NEW, SUBMITTED, REJECTED, OPEN)
- `date` (Optional) date the report is created in the datetime format "2013-03-30T09:04:56.123" will default to now
- `advance` (Optional) Numberic advance amount
- `costCenter` (Optional) If not provided will look in the users profile for the default value
- `employeeId` (Optional) If not provided will look in the users profile for the default value
- `employeeCompany` (Optional) If not provided will look in the users profile for the default value
- `ccy` (Optional) The currency symbol. Currently supported are 'EUR, GBP, USD'  TODO provide the client with  a list of ccy codes
- `receiptIds` (Optional) comma seperated list of receitp ids to attach to the report
- `notes` (Optional) Notes attached to the report


Curl example: 


`curl -b cookies.txt -c cookies.txt -i -k --insecure -X PUT -H "Content-Type: application/json" -d '{"name":"Second Mobile Invoice report", "date":"2013-03-30", "from":"2014-03-30", "to":"2014-04-30", "discount":"100.00", "ccy":"GBP", "receiptIds":"6,7", "reportStatus":"OPEN", "advance":"100.00", "costCenter":"33398-9909-99", "employeeId":"EMP-8898-JJK"}' https://hikalu.com/mobile/report/EXPENSE`

+ Parameters
    + reportType (string, required, `string value representing an enum`) ... Valid value IS "EXPENSE"


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "name":"fiskl expense 2", 
                "date":"2013-03-30", 
                "from":"2014-03-30", 
                "to":"2014-04-30", 
                "discount":"100.00", 
                "ccy":"GBP", 
                "reportStatus":"OPEN", 
                "advance":"100.00", 
                "costCenter":"33398-9909-99", 
                "employeeId":"EMP-8898-JJK",
                "employeeCompany":"fiskl inc",
                "receiptIds":"13",
                "notes":"Some notes to be added to the report"
            }

+ Response 200 (application/json)

            {
                message: "Successfully created report name=fiskl expense 2"
                id: 44
            }
        
        
+ Response 400 (application/json)

            {"reportType":["Invalid value"],"reportStatus":["Invalid value"]}   

## Delete an Expense Report [/mobile/report/{reportType}/{reportId}]
### Delete Report API [DELETE]

If the report has invoices attached these will be unattached. 
You can not delete the report if its been submitted

Curl example: 


`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X DELETE  https://hikalu.com/mobile/report/61`

+ Parameters
    + reportId (long, required, `numerice value representing a long`) ... The id of the `report` to delete
    + reportType (string, required, `string value representing reportType`, values 'EXPENSE') The only valid value is EXPENSE


+ Request 

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79


+ Response 200 (application/json)

        {
          "message": "Successfully deleted expense report id=100"
        }

+ Response 404 (application/json)

        {
          "message": "Report id=100 not found"
        }

+ Response 400 (application/json)

        {
          "message": "Unable to delete resource with status=submitted"
        }
        
## Email report [/mobile/report/email/{reportType}/{id}]
### Email report [POST]    

Report can be emailed 

This resource has the following attributes

- `to`  (Required) to email address of who we are sending the report to
- `from` (Optional )  If you want a different from to the address registered on the users account
- `copy`  (Optional) True or False, does the user want to be coppied onto the email i.e sent a copy of the email
- `cc`  (Optional) Any other email addresses to cc the email to
- `memo` (optional) Notes which will appear as text on the email


Curl examples:

`curl -b cookies.txt -c cookies.txt -i  -k --insecure -X POST -H "Content-Type: application/json" -d '{"to":"svader@gmail.com","from":"svader@gmail.com", "memo":"Pay me now!"}'  https://hikalu.com/mobile/report/email/2`


+ Parameters
    + id (string, required, `numerice value representing a long`) ... The id of the `user` to retrieve
    + reportType (string, required, `string value representing reportType`, values 'EXPENSE') The only valid value is EXPENSE


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79

    + Body

            {
                "to":"svader@gmail.com",
                "from":"svader@gmail.com", 
                "memo":"Pay me now!"
            }
        
+ Response 200 (application/json)


            {
                message: "Successfully emailed expense report"
            }
            

## Update Report [/mobile/report/{reportType}/{id}]
### Update report [POST]  TODO



# Reference Data
Reference data

## Retreive all currencies [/data/currencies]
### Retreive all currencies [GET]  
Returns all the supported currencies

Curl examples


`curl -b cookies.txt -c cookies.txt -i -k --insecure -X GET https://hikalu.com/data/currencies`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79



+ Response 200 (application/json)

    + Body
    
            [
                {
                "id": 1,
                "code": "AED",
                "name": "UAE Dirham",
                "symbol": "",
                "euro": false
                },
                {
                "id": 8,
                "code": "AUD",
                "name": "Australian Dollar",
                "symbol": "$",
                "euro": false
                },
                {
                "id": 24,
                "code": "BWP",
                "name": "Pula",
                "symbol": "P",
                "euro": false
                },
                {
                "id": 49,
                "code": "EUR",
                "name": "Euro",
                "symbol": "\u20ac",
                "euro": true
                },
                {
                "id": 49,
                "code": "EUR",
                "name": "Euro",
                "symbol": "\u20ac",
                "euro": true
                },
                {
                "id": 52,
                "code": "GBP",
                "name": "Pound Sterling",
                "symbol": "\u00a3",
                "euro": false
                },
                {
                "id": 60,
                "code": "HKD",
                "name": "Hong Kong Dollar",
                "symbol": "$",
                "euro": false
                },
                {
                "id": 67,
                "code": "INR",
                "name": "Indian Rupee",
                "symbol": "",
                "euro": false
                },
                {
                "id": 49,
                "code": "EUR",
                "name": "Euro",
                "symbol": "\u20ac",
                "euro": true
                },
                {
                "id": 52,
                "code": "GBP",
                "name": "Pound Sterling",
                "symbol": "\u00a3",
                "euro": false
                },
                {
                "id": 49,
                "code": "EUR",
                "name": "Euro",
                "symbol": "\u20ac",
                "euro": true
                },
                {
                "id": 110,
                "code": "NZD",
                "name": "New Zealand Dollar",
                "symbol": "$",
                "euro": false
                },
                {
                "id": 120,
                "code": "RON",
                "name": "New Romanian Leu",
                "symbol": "lei",
                "euro": false
                },
                {
                "id": 129,
                "code": "SGD",
                "name": "Singapore Dollar",
                "symbol": "$",
                "euro": false
                },
                {
                "id": 152,
                "code": "USS",
                "name": "US Dollar (Same day)",
                "symbol": "",
                "euro": false
                },
                {
                "id": 159,
                "code": "WST",
                "name": "Tala",
                "symbol": "",
                "euro": false
                },
                {
                "id": 178,
                "code": "ZAR",
                "name": "Rand",
                "symbol": "R",
                "euro": false
                }
                ]
            

## Retreive all countries [/data/countries]
### Retreive all valid countries [GET] 

Returns all the supported countries

Curl examples


`curl -b cookies.txt -c cookies.txt -i -k --insecure -X GET https://hikalu.com/data/countries`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79



+ Response 200 (application/json)

    + Body
    
            [
                {
                "id": 2,
                "code": "AE",
                "nameEn": "United Arab Emirates",
                "nameFr": "\u00c9mirats arabes unis",
                "currencyId": 1,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 1,
                  "code": "AED",
                  "name": "UAE Dirham",
                  "symbol": "",
                  "euro": false
                }
                },
                {
                "id": 13,
                "code": "AU",
                "nameEn": "Australia",
                "nameFr": "Australie",
                "currencyId": 8,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 8,
                  "code": "AUD",
                  "name": "Australian Dollar",
                  "symbol": "$",
                  "euro": false
                }
                },
                {
                "id": 35,
                "code": "BW",
                "nameEn": "Botswana",
                "nameFr": "Botswana",
                "currencyId": 24,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 24,
                  "code": "BWP",
                  "name": "Pula",
                  "symbol": "P",
                  "euro": false
                }
                },
                {
                "id": 68,
                "code": "ES",
                "nameEn": "Spain",
                "nameFr": "Espagne",
                "currencyId": 49,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 49,
                  "code": "EUR",
                  "name": "Euro",
                  "symbol": "\u20ac",
                  "euro": true
                }
                },
                {
                "id": 75,
                "code": "FR",
                "nameEn": "France",
                "nameFr": "France",
                "currencyId": 49,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 49,
                  "code": "EUR",
                  "name": "Euro",
                  "symbol": "\u20ac",
                  "euro": true
                }
                },
                {
                "id": 77,
                "code": "GB",
                "nameEn": "United Kingdom",
                "nameFr": "Royaume-Uni",
                "currencyId": 52,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 52,
                  "code": "GBP",
                  "name": "Pound Sterling",
                  "symbol": "\u00a3",
                  "euro": false
                }
                },
                {
                "id": 95,
                "code": "HK",
                "nameEn": "Hong Kong",
                "nameFr": "Hong Kong",
                "currencyId": 60,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 60,
                  "code": "HKD",
                  "name": "Hong Kong Dollar",
                  "symbol": "$",
                  "euro": false
                }
                },
                {
                "id": 105,
                "code": "IN",
                "nameEn": "India",
                "nameFr": "Inde",
                "currencyId": 67,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 67,
                  "code": "INR",
                  "name": "Indian Rupee",
                  "symbol": "",
                  "euro": false
                }
                },
                {
                "id": 110,
                "code": "IT",
                "nameEn": "Italy",
                "nameFr": "Italie",
                "currencyId": 49,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 49,
                  "code": "EUR",
                  "name": "Euro",
                  "symbol": "\u20ac",
                  "euro": true
                }
                },
                {
                "id": 111,
                "code": "JE",
                "nameEn": "Jersey",
                "nameFr": "Jersey",
                "currencyId": 52,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 52,
                  "code": "GBP",
                  "name": "Pound Sterling",
                  "symbol": "\u00a3",
                  "euro": false
                }
                },
                {
                "id": 166,
                "code": "NL",
                "nameEn": "The Netherlands",
                "nameFr": "Pays-Bas",
                "currencyId": 49,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 49,
                  "code": "EUR",
                  "name": "Euro",
                  "symbol": "\u20ac",
                  "euro": true
                }
                },
                {
                "id": 171,
                "code": "NZ",
                "nameEn": "New Zealand",
                "nameFr": "Nouvelle-Z\u00e9lande",
                "currencyId": 110,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 110,
                  "code": "NZD",
                  "name": "New Zealand Dollar",
                  "symbol": "$",
                  "euro": false
                }
                },
                {
                "id": 189,
                "code": "RO",
                "nameEn": "Romania",
                "nameFr": "Roumanie",
                "currencyId": 120,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 120,
                  "code": "RON",
                  "name": "New Romanian Leu",
                  "symbol": "lei",
                  "euro": false
                }
                },
                {
                "id": 198,
                "code": "SG",
                "nameEn": "Singapore",
                "nameFr": "Singapour",
                "currencyId": 129,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 129,
                  "code": "SGD",
                  "name": "Singapore Dollar",
                  "symbol": "$",
                  "euro": false
                }
                },
                {
                "id": 233,
                "code": "US",
                "nameEn": "United States",
                "nameFr": "\u00c9tats-Unis",
                "currencyId": 152,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 152,
                  "code": "USS",
                  "name": "US Dollar (Same day)",
                  "symbol": "",
                  "euro": false
                }
                },
                {
                "id": 244,
                "code": "WS",
                "nameEn": "Samoa",
                "nameFr": "Samoa",
                "currencyId": 159,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 159,
                  "code": "WST",
                  "name": "Tala",
                  "symbol": "",
                  "euro": false
                }
                },
                {
                "id": 247,
                "code": "ZA",
                "nameEn": "South Africa",
                "nameFr": "Afrique du Sud",
                "currencyId": 178,
                "supported": true,
                "taxYear": [
                  
                ],
                "valid": true,
                "currency": {
                  "id": 178,
                  "code": "ZAR",
                  "name": "Rand",
                  "symbol": "R",
                  "euro": false
                }
                }
                ]

## Retreive all rates [/data/rates]
### Retreive all rates [GET] 
Curl examples


`curl -b cookies.txt -c cookies.txt -i -k --insecure -X GET https://hikalu.com/data/rates`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79



+ Response 200 (application/json)

    + Body
    
            {
              "DateTime": "1405596607",
              "USD": "1",
              "AED": "3.673\r",
              "AFN": "56.12\r",
              "ALB": "103.58\r",
              "AMD": "407.19\r",
              "ANG": "1.79\r",
              "AOA": "96.96\r",
              "ARS": "8.1476\r",
              "AUD": "1.0666\r",
              "AWG": "1.7898\r",
              "AZN": "0.7843\r",
              "BAM": "1.4489\r",
              "BBD": "2.00\r",
              "BDT": "77.59\r",
              "BGN": "1.446\r",
              "BHD": "0.377\r",
              "BIF": "1520.00\r",
              "BMD": "1.00\r",
              "BND": "1.2409\r",
              "BOB": "6.91\r",
              "BRL": "2.2123\r",
              "BSD": "1.00\r",
              "BTN": "60.13\r",
              "BWP": "8.8574\r",
              "BYR": "10265.00\r",
              "BZD": "1.995\r",
              "CAD": "1.0748\r",
              "CDF": "924.00\r",
              "CHF": "0.8979\r",
              "CLF": "0.0233\r",
              "CLP": "559.36\r",
              "CNY": "6.2045\r",
              "COP": "1865.50\r",
              "CRC": "548.50\r",
              "CUP": "1.00\r",
              "CVE": "80.49\r",
              "CZK": "20.283\r",
              "DJF": "181.20\r",
              "DKK": "5.5122\r",
              "DOP": "43.30\r",
              "DZD": "79.505\r",
              "EGP": "7.1497\r",
              "ETB": "19.7355\r",
              "EUR": "0.7392\r",
              "FJD": "1.8159\r",
              "FKP": "0.5842\r",
              "GBP": "0.5846\r",
              "GEL": "1.7542\r",
              "GHS": "3.3595\r",
              "GIP": "0.5842\r",
              "GMD": "39.60\r",
              "GNF": "7050.00\r",
              "GTQ": "7.7465\r",
              "GYD": "208.45\r",
              "HKD": "7.751\r",
              "HNL": "20.9569\r",
              "HRK": "5.6319\r",
              "HTG": "45.3209\r",
              "HUF": "229.505\r",
              "IDR": "11686.00\r",
              "IEP": "0.5821\r",
              "ILS": "3.41\r",
              "INR": "60.1755\r",
              "IQD": "1163.80\r",
              "IRR": "26025.00\r",
              "ISK": "114.50\r",
              "JMD": "112.28\r",
              "JOD": "0.7086\r",
              "JPY": "101.4525\r",
              "KES": "87.70\r",
              "KGS": "51.6714\r",
              "KHR": "4045.00\r",
              "KMF": "363.6529\r",
              "KPW": "900.00\r",
              "KRW": "1028.6851\r",
              "KWD": "0.2823\r",
              "KZT": "183.51\r",
              "LAK": "8054.50\r",
              "LBP": "1512.50\r",
              "LKR": "130.27\r",
              "LRD": "91.50\r",
              "LSL": "10.68\r",
              "LTL": "2.5523\r",
              "LVL": "0.5193\r",
              "LYD": "1.2375\r",
              "MAD": "8.2744\r",
              "MDL": "13.985\r",
              "MGA": "2410.00\r",
              "MKD": "45.475\r",
              "MMK": "972.00\r",
              "MNT": "1833.88\r",
              "MOP": "7.9835\r",
              "MRO": "290.90\r",
              "MUR": "30.40\r",
              "MVR": "15.39\r",
              "MWK": "395.78\r",
              "MXN": "12.9415\r",
              "MYR": "3.1765\r",
              "MZN": "30.90\r",
              "NAD": "10.669\r",
              "NGN": "161.83\r",
              "NIO": "26.015\r",
              "NOK": "6.1975\r",
              "NPR": "97.32\r",
              "NZD": "1.1513\r",
              "OMR": "0.385\r",
              "PAB": "1.00\r",
              "PEN": "2.789\r",
              "PGK": "2.4399\r",
              "PHP": "43.54\r",
              "PKR": "98.83\r",
              "PLN": "3.0619\r",
              "PYG": "4193.0698\r",
              "QAR": "3.6406\r",
              "RON": "3.2845\r",
              "RSD": "85.8705\r",
              "RUB": "34.988\r",
              "RWF": "680.50\r",
              "SAR": "3.7503\r",
              "SBD": "7.2209\r",
              "SCR": "12.2036\r",
              "SDG": "5.6942\r",
              "SEK": "6.8298\r",
              "SGD": "1.2415\r",
              "SHP": "0.5842\r",
              "SLL": "4340.00\r",
              "SOS": "945.00\r",
              "SRD": "3.275\r",
              "STD": "18030.00\r",
              "SVC": "8.747\r",
              "SYP": "149.70\r",
              "SZL": "10.6825\r",
              "THB": "32.16\r",
              "TJS": "4.941\r",
              "TMT": "2.85\r",
              "TND": "1.7182\r",
              "TOP": "1.8404\r",
              "TRY": "2.1236\r",
              "TTD": "6.3699\r",
              "TWD": "29.985\r",
              "TZS": "1658.50\r",
              "UAH": "11.723\r",
              "UGX": "2627.00\r",
              "UYU": "22.90\r",
              "UZS": "2324.1001\r",
              "VEF": "6.2925\r",
              "VND": "21175.00\r",
              "VUV": "93.55\r",
              "WST": "2.2965\r",
              "XAF": "484.8705\r",
              "XCD": "2.70\r",
              "XDR": "0.6488\r",
              "XOF": "485.35\r",
              "XPF": "88.70\r",
              "YER": "214.855\r",
              "ZAR": "10.7147\r",
              "ZMK": "5189.50\r",
              "ZWL": "322.355\r"
            }
            

# Group Notifications
Notifications data


## Retreive all notifications [/mobile/notifications/{notification type}]
### Retreive all notifications [GET]  
Returns all the Notifications

Curl examples


`curl -b cookies.txt -c cookies.txt -k --insecure -X GET -H "Content-Type: application/json" -d '{"from":"2013-03-30T09:04:56.123", "limit":"2"}' https://hikalu.com/mobile/notifications  | python -m json.tool`

+ Parameters
    + notificationType (string, optional, `string value representing an enmu`) ... Valid values are "NEW_USER,INVOICE_REJECTED,</br>PAYMENT_REJECTED,</br>APPROVAL_REQUIRED,</br>PAYMENT_OVERDUE"


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79



+ Response 404 (application/json)

            {
                "message": "UNKNOWN is an invalid value. Possible values are NEW_USER,INVOICE_REJECTED,PAYMENT_REJECTED,APPROVAL_REQUIRED,PAYMENT_OVERDUE,UNKNOWN"
            }
            
            
+ Response 200 (application/json)

    + Body          
    
    
            [
                {
                    "active": true,
                    "created": "24-Jul-2014T17:05:55",
                    "id": 21,
                    "localUser": {
                        "localUser": {
                            "country": "GB",
                            "enabled": true,
                            "firstName": null,
                            "id": 41,
                            "lastName": null,
                            "verified": false
                        }
                    },
                    "reason": "Created new user LocalUser id=41, name=Shawn, lastName=Vader, email=shawn@expensepa.com, enabled=true, verified=false",
                    "timestamp": 1406217955144,
                    "type": "NEW_USER"
                },
                {
                    "active": true,
                    "created": "25-Jul-2014T09:01:47",
                    "dueDate": "24-Jul-2014T00:00:00",
                    "id": 41,
                    "localUser": {
                        "localUser": {
                            "country": "GB",
                            "enabled": true,
                            "firstName": "Shawn",
                            "id": 41,
                            "lastName": "Vader",
                            "verified": false
                        }
                    },
                    "reason": "Due date is overdue. Was due on 2014-07-24T00:00:00.000+01:00",
                    "timestamp": 1406275307460,
                    "type": "PAYMENT_OVERDUE"
                }
            ]
    

## Update notification to read [/mobile/notifications/read/{id}]
### Update notification to read [POST]  
Returns all the Notifications

Curl examples


`curl -b cookies.txt -c cookies.txt -k --insecure -X POST  https://hikalu.com/mobile/notifications/read/21  | python -m json.tool`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79



+ Response 404 (application/json)

            {
                "message": "notification for id=2 not found for user=LocalUser id=41, name=Shawn, lastName=Vader, email=shawn@expensepa.com, enabled=true, verified=false"
            }
            
            
+ Response 200 (application/json)

    + Body          
    
    
            {
                "message": "Successfully updated notification id=21 for user=LocalUser id=41, name=Shawn, lastName=Vader, email=shawn@expensepa.com, enabled=true, verified=false to read"
            }

## Update notifications to read [/mobile/notifications/read]
### Update notifications to read [POST]  
Returns all the Notifications

This resource has the following attributes

- `ids`  (Required) comma separated list of ids


Curl examples


`curl -b cookies.txt -c cookies.txt -k --insecure -X POST  https://hikalu.com/mobile/notifications/read  | python -m json.tool`


+ Request (application/json)

    + Header
     
            Cookie: xpa-dev=699181b8327d97058deb693a032dbbd26c96360b33c81b9e5d74d3be656e20e4c2f1a1484f00ab17bc8f89b91a51f03eb47d51ec833738c975e786eb84fac026c2b79adc3ecab51c2dd36e222454f3fe423e739044608d79



+ Response 404 (application/json)

            {
                "message":"Expecting comma separated list of ids in parameter 'ids'"
            }
            
            
+ Response 200 (application/json)

    + Body          
    
    
            {
                "message":"Successfully updated notifications Updated the following notifications - 21 41  for user=LocalUser id=41, name=Shawn, lastName=Vader, email=shawn@expensepa.com, enabled=true, verified=false "
            }

        